AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: The ID of the VPC in which to create the Amazon MSK cluster.
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: A list of subnet IDs in which to create the Amazon MSK cluster.
  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: The ID of the security group for the Amazon MSK cluster.
Resources:
  MSKCluster:
    Type: 'AWS::MSK::Cluster'
    Properties:
      BrokerNodeGroupInfo:
        BrokerAZDistribution: DEFAULT
        ClientSubnets: !Ref SubnetIds
        InstanceType: kafka.m5.large
        SecurityGroups:
          - !Ref SecurityGroupId
      ClusterName: my-msk-cluster
      EncryptionInfo:
        EncryptionAtRest:
          DataVolumeKMSKeyId: alias/aws/msk
        EncryptionInTransit:
          ClientBroker: TLS
      EnhancedMonitoring: PER_BROKER
      KafkaVersion: '2.7.0'
      NumberOfBrokerNodes: 3
      OpenMonitoring:
        Prometheus:
          JmxExporter:
            EnabledInBroker: true
        ConfigurationInfo:
          Arn: arn:aws:cm:us-west-2:123456789012:config/MyJMXExporterConfig
          Revision: 2
          Type: JMX_EXPORTER
      LoggingInfo:
        BrokerLogs:
          CloudWatchLogs:
            Enabled: true
            LogGroup: /aws/kafka/broker
            RetentionInDays: 7
  MSKClusterIAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - kafka.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: 'msk-access'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'msk:*'
                Resource: !Sub 'arn:aws:msk:${AWS::Region}:${AWS::AccountId}:cluster/${MSKCluster}'
Outputs:
  MSKClusterArn:
    Value: !Sub 'arn:aws:msk:${AWS::Region}:${AWS::AccountId}:cluster/${MSKCluster}'
    Description: The Amazon Resource Name (ARN) of the Amazon MSK cluster.
  MSKClusterBootstrapServers:
    Value: !Join
      - ','
      - !GetAtt MSKCluster.BootstrapBrokers
    Description: A comma-separated list of bootstrap brokers that can be used to connect to the Amazon MSK cluster.
