Parameters:
  StreamName:
    Type: String
    Default: YourKinesisStreamName
  ShardCount:
    Type: Number
    Default: 1
  RetentionPeriodHours:
    Type: Number
    Default: 24

Resources:
  KinesisStream:
    Type: AWS::Kinesis::Stream
    Properties: 
      Name: !Ref StreamName
      RetentionPeriodHours: !Ref RetentionPeriodHours
      ShardCount: !Ref ShardCount